if [ "${CONDA_BUILD_CROSS_COMPILATION:-0}" = "1" ] && \
   [ -n "${CROSSCOMPILING_EMULATOR:-}" ] && \
   [ -z "${CMAKE_CROSSCOMPILING_EMULATOR+x}" ]; then
  export CMAKE_CROSSCOMPILING_EMULATOR="$CROSSCOMPILING_EMULATOR"
  export _CMAKE_CROSSCOMPILING_EMULATOR_ACTIVATED=1
fi
