{% set version = "3.13.4" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://gitlab.kitware.com/cmake/cmake/-/archive/v{{ version }}/cmake-v{{ version }}.tar.bz2
  fn: cmake-{{ version }}.tar.gz
  sha256: 06fc6d01e584802d071d1ed8eaaaeffa890469e4b2a95783cc5a3d1a55f1e347

build:
  number: 1
  skip: True  # [win and vc<14]
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make            # [unix]

  host:
    - bzip2           # [unix]
    - curl 7.61.1           # [unix]
    - expat           # [unix]
    - ncurses         # [unix]
    - xz              # [unix]
    - zlib            # [unix]
    - libuv           # [unix]
    - rhash           # [unix]

  run:
    - bzip2           # [unix]
    - curl            # [unix]
    - expat           # [unix]
    - ncurses         # [unix]
    - xz              # [unix]
    - zlib            # [unix]
    - libuv           # [unix]
    - rhash           # [unix]
    - vs2015_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version
    - ccmake --version  # [unix]

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
