{% set major_minor = "3.6" %}
{% set version = major_minor + ".2" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz              # [not win]
  fn: cmake-{{ version }}.tar.gz                                                          # [not win]
  sha256: 189ae32a6ac398bb2f523ae77f70d463a6549926cde1544cd9cc7c6609f8b346                # [not win]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win32-x86.zip       # [win32]
  fn: cmake-{{ version }}-win32-x86.zip                                                   # [win32]
  sha256: 613eec5a8b2e2c49826e0e8e18f516b6f2b481309ae55925d226ce8ab78b0fba                # [win32]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
  fn: cmake-{{ version }}-win64-x64.zip                                                   # [win64]
  sha256: 61337a0528fc3902d7f2f7594959aa6aa48a52863dd2da335a0e248b5eb8acaf                # [win64]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:        # [unix]
  build:             # [unix]
    - toolchain      # [unix]
    - bzip2 1.0.*    # [unix]
    - curl           # [unix]
    - expat          # [unix]
    - jsoncpp        # [unix]
    - libarchive     # [unix]
    - ncurses 5.9*   # [unix]
    - xz 5.2.*       # [unix]
    - zlib 1.2.*     # [unix]

  run:               # [unix]
    - bzip2 1.0.*    # [unix]
    - curl           # [unix]
    - expat          # [unix]
    - jsoncpp        # [unix]
    - libarchive     # [unix]
    - ncurses 5.9*   # [unix]
    - xz 5.2.*       # [unix]
    - zlib 1.2.*     # [unix]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - ocefpaf
    - msarahan
    - scopatz
