{% set major_minor = "3.10" %}
{% set version = major_minor + ".0" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz
  fn: cmake-{{ version }}.tar.gz
  sha256: b3345c17609ea0f039960ef470aa099de9942135990930a57c14575aae884987

  patches:
    # Revert the whole commit in 3.11
    - flang-fix.patch
    - cmake-3.10-boost-1.66-support.patch

build:
  number: 3
  detect_binary_files_with_prefix: true
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - bzip2 1.0.*
    - curl >=7.44.0,<8
    - expat
    - ncurses 5.9*  # [unix]
    - xz 5.2.*
    - zlib 1.2.11
    - libuv  # [unix]
    - rhash  # [unix]

  run:
    - bzip2 1.0.*
    - curl >=7.44.0,<8
    - expat
    - ncurses 5.9*  # [unix]
    - xz 5.2.*
    - zlib 1.2.11
    - libuv  # [unix]
    - rhash  # [unix]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
