schema_version: 1

context:
  version: "4.4.3"
  maj_min: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: cmake
  version: ${{ version }}

source:
  url: https://github.com/Kitware/CMake/releases/download/v${{ version }}/cmake-${{ version }}.tar.gz
  sha256: c46400618b4f1f2b43507f24fb22f3ae830c3416cf23b776e16e1d413aa892f0

build:
  number: 0
  script:
    env:
      MAJOR_MINOR: ${{ maj_min }}

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ninja
    - if: unix
      then: cmake-no-system
      else: 7zip

  host:
    - bzip2
    - libcurl
    - expat
    - liblzma-devel
    - zlib
    - libuv
    - zstd
    - if: unix
      then:
        - ncurses
        - rhash
  ignore_run_exports:
    by_name:
      - vc

tests:
  - script:
      - cmake --version
      - ctest --version
      - cpack --version
      - ccmake --version
      - if: unix
        then:
          - test ! -d $PREFIX/doc
        else:
          - if exist %LIBRARY_PREFIX%\\doc exit 1

about:
  homepage: https://cmake.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.rst
    - Utilities/cmcppdap/LICENSE
    - Utilities/cmlibarchive/COPYING
    - Utilities/cmjsoncpp/LICENSE
    - if: win
      then:
        - Utilities/cmlibrhash/COPYING
        - Utilities/cmpdcurses/README.md
        - Utilities/cmpdcurses/wincon/README.md
  summary: CMake is an extensible, open-source system that manages the build process
  documentation: https://cmake.org/documentation
  repository: https://gitlab.kitware.com/cmake/cmake

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
    - marcelotrevisani
